[versions]
kotlin = "2.2.20"
ktor = "3.3.0"
koin = "3.5.6"
logback = "1.4.14"
kotlin-asyncapi-ktor = "3.1.2"
mcp = "0.7.4"
okio = "3.12.0"

[libraries]
kotlin-asyncapi-ktor = { module = "org.openfolder:kotlin-asyncapi-ktor", version.ref = "kotlin-asyncapi-ktor" }
mcp-kotlin-sdk = { module = "io.modelcontextprotocol:kotlin-sdk", version.ref = "mcp" }
ktor-server-core = { module = "io.ktor:ktor-server-core" }
ktor-server-sse = { module = "io.ktor:ktor-server-sse" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio" }
ktor-server-cio = { group = "io.ktor", name = "ktor-server-cio"}
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }